flags: {}
packages:
- .
extra-deps:
  - binary-search-0.9
  - hoopl-3.10.2.0
  - lattices-1.4.1
  - universe-base-1.0.2.1
  - universe-instances-base-1.0
  - universe-reverse-instances-1.0

resolver: lts-4.2
# skip-ghc-check: True
